"""
Feature engineering module for Amazon Business Entity Resolution Challenge 2026.

Computes pairwise string, token, numerical, and structural similarity features
for candidate pairs generated by the blocking module using normalized attributes.
"""

from typing import Dict, List, Optional, Set, Tuple
import pandas as pd
import numpy as np

# RapidFuzz for high-performance C++ string matching with difflib fallback
try:
    from rapidfuzz import distance, fuzz
    _HAS_RAPIDFUZZ = True
except ImportError:
    import difflib
    _HAS_RAPIDFUZZ = False

from src.normalization import add_normalized_features


# ---------------------------------------------------------------------------
# String Distance & Similarity Helpers
# ---------------------------------------------------------------------------

def _levenshtein_ratio(s1: str, s2: str) -> float:
    """Calculates normalized Levenshtein similarity ratio in [0.0, 1.0]."""
    if not s1 or not s2:
        return 1.0 if not s1 and not s2 else 0.0
    if s1 == s2:
        return 1.0
    if _HAS_RAPIDFUZZ:
        return float(fuzz.ratio(s1, s2)) / 100.0
    return float(difflib.SequenceMatcher(None, s1, s2).ratio())


def _jaro_winkler_similarity(s1: str, s2: str) -> float:
    """Calculates Jaro-Winkler similarity score in [0.0, 1.0]."""
    if not s1 or not s2:
        return 1.0 if not s1 and not s2 else 0.0
    if s1 == s2:
        return 1.0
    if _HAS_RAPIDFUZZ:
        return float(distance.JaroWinkler.similarity(s1, s2))
    
    # Pure Python Jaro-Winkler implementation fallback
    len1, len2 = len(s1), len(s2)
    max_dist = (max(len1, len2) // 2) - 1
    if max_dist < 0:
        max_dist = 0

    s1_matches = [False] * len1
    s2_matches = [False] * len2

    matches = 0
    transpositions = 0

    for i in range(len1):
        start = max(0, i - max_dist)
        end = min(i + max_dist + 1, len2)
        for j in range(start, end):
            if s2_matches[j]:
                continue
            if s1[i] != s2[j]:
                continue
            s1_matches[i] = True
            s2_matches[j] = True
            matches += 1
            break

    if matches == 0:
        return 0.0

    k = 0
    for i in range(len1):
        if not s1_matches[i]:
            continue
        while not s2_matches[k]:
            k += 1
        if s1[i] != s2[k]:
            transpositions += 1
        k += 1

    jaro = (
        (matches / len1) + (matches / len2) + ((matches - transpositions / 2) / matches)
    ) / 3.0

    # Winkler prefix bonus (up to 4 prefix chars)
    prefix = 0
    for i in range(min(4, min(len1, len2))):
        if s1[i] == s2[i]:
            prefix += 1
        else:
            break

    return float(jaro + prefix * 0.1 * (1.0 - jaro))


def _token_sort_ratio(s1: str, s2: str) -> float:
    """Calculates token sort similarity ratio in [0.0, 1.0]."""
    if not s1 or not s2:
        return 1.0 if not s1 and not s2 else 0.0
    if s1 == s2:
        return 1.0
    if _HAS_RAPIDFUZZ:
        return float(fuzz.token_sort_ratio(s1, s2)) / 100.0

    sorted1 = " ".join(sorted(s1.split()))
    sorted2 = " ".join(sorted(s2.split()))
    return _levenshtein_ratio(sorted1, sorted2)


def _token_set_ratio(s1: str, s2: str) -> float:
    """Calculates token set similarity ratio in [0.0, 1.0]."""
    if not s1 or not s2:
        return 1.0 if not s1 and not s2 else 0.0
    if s1 == s2:
        return 1.0
    if _HAS_RAPIDFUZZ:
        return float(fuzz.token_set_ratio(s1, s2)) / 100.0

    set1 = set(s1.split())
    set2 = set(s2.split())
    intersection = set1 & set2
    if not intersection:
        return _levenshtein_ratio(s1, s2)

    sorted_intersection = " ".join(sorted(intersection))
    sorted1 = " ".join(sorted(set1))
    sorted2 = " ".join(sorted(set2))

    r1 = _levenshtein_ratio(sorted_intersection, sorted1)
    r2 = _levenshtein_ratio(sorted_intersection, sorted2)
    r3 = _levenshtein_ratio(sorted1, sorted2)
    return max(r1, r2, r3)


def _jaccard_similarity(tokens1: List[str], tokens2: List[str]) -> float:
    """Calculates Jaccard similarity between two token lists in [0.0, 1.0]."""
    if not tokens1 or not tokens2:
        return 0.0
    set1, set2 = set(tokens1), set(tokens2)
    intersection = len(set1 & set2)
    union = len(set1 | set2)
    return float(intersection / union) if union > 0 else 0.0


# ---------------------------------------------------------------------------
# Feature Computation Engine
# ---------------------------------------------------------------------------

def _ensure_normalized(df: pd.DataFrame) -> pd.DataFrame:
    """Ensures DataFrame has normalized derived columns from normalization.py."""
    required_cols = [
        "business_name_normalized",
        "business_name_core",
        "business_name_tokens",
        "business_address_normalized",
        "address_tokens",
        "address_numbers",
        "postal_code",
        "country_normalized",
    ]
    if not all(col in df.columns for col in required_cols):
        return add_normalized_features(df)
    return df


def compute_pair_features(
    candidates_df: pd.DataFrame,
    df_s1: pd.DataFrame,
    df_target: pd.DataFrame,
) -> pd.DataFrame:
    """
    Computes numerical comparison features for each candidate pair generated by blocking.

    Features Produced:
    1. name_levenshtein_ratio: Levenshtein ratio on business_name_normalized.
    2. name_jaro_winkler: Jaro-Winkler similarity on business_name_normalized.
    3. core_name_levenshtein_ratio: Levenshtein ratio on business_name_core.
    4. core_name_token_sort_ratio: Token sort ratio on business_name_core.
    5. core_name_token_set_ratio: Token set ratio on business_name_core.
    6. name_token_jaccard: Jaccard overlap on business_name_tokens.
    7. address_levenshtein_ratio: Levenshtein ratio on business_address_normalized.
    8. address_token_jaccard: Jaccard overlap on address_tokens.
    9. postal_code_match: 1.0 if postal codes match and are non-empty, else 0.0.
    10. address_number_match: 1.0 if address house/unit numbers overlap, else 0.0.
    11. country_match: 1.0 if country_normalized matches, else 0.0.
    12. is_address_missing: 1.0 if either address is empty "", else 0.0.

    Args:
        candidates_df: DataFrame containing ['source1_entity_id', 'candidate_entity_id'].
        df_s1: Source 1 DataFrame.
        df_target: Target (Source 2 or 3) DataFrame.

    Returns:
        DataFrame containing candidate IDs and 12 numerical feature columns.
    """
    # Detect target entity ID column name in candidates_df
    target_cand_col = (
        "target_entity_id"
        if "target_entity_id" in candidates_df.columns
        else "candidate_entity_id"
    )

    if candidates_df.empty:
        cols = [
            "source1_entity_id",
            target_cand_col,
            "name_levenshtein_ratio",
            "name_jaro_winkler",
            "core_name_levenshtein_ratio",
            "core_name_token_sort_ratio",
            "core_name_token_set_ratio",
            "name_token_jaccard",
            "address_levenshtein_ratio",
            "address_token_jaccard",
            "postal_code_match",
            "address_number_match",
            "country_match",
            "is_address_missing",
        ]
        return pd.DataFrame(columns=cols)

    s1_norm = _ensure_normalized(df_s1)
    target_norm = _ensure_normalized(df_target)

    s1_id_col = "entity_id" if "entity_id" in s1_norm.columns else s1_norm.columns[0]
    target_id_col = (
        "entity_id" if "entity_id" in target_norm.columns else target_norm.columns[0]
    )

    # Index normalized records by ID for O(1) row access
    s1_dict = s1_norm.set_index(s1_id_col).to_dict("index")
    target_dict = target_norm.set_index(target_id_col).to_dict("index")

    feature_rows = []

    for pair in candidates_df.itertuples(index=False):
        s1_id = getattr(pair, "source1_entity_id")
        target_id = getattr(pair, target_cand_col)

        if s1_id not in s1_dict or target_id not in target_dict:
            continue

        r1 = s1_dict[s1_id]
        r2 = target_dict[target_id]

        # Extract normalized attributes
        n1 = r1.get("business_name_normalized", "")
        n2 = r2.get("business_name_normalized", "")

        c1 = r1.get("business_name_core", "")
        c2 = r2.get("business_name_core", "")

        ntok1 = r1.get("business_name_tokens", [])
        ntok2 = r2.get("business_name_tokens", [])

        a1 = r1.get("business_address_normalized", "")
        a2 = r2.get("business_address_normalized", "")

        atok1 = r1.get("address_tokens", [])
        atok2 = r2.get("address_tokens", [])

        num1 = r1.get("address_numbers", [])
        num2 = r2.get("address_numbers", [])

        post1 = r1.get("postal_code", "")
        post2 = r2.get("postal_code", "")

        cntry1 = r1.get("country_normalized", "")
        cntry2 = r2.get("country_normalized", "")

        # Compute feature metrics
        feat_name_lev = _levenshtein_ratio(n1, n2)
        feat_name_jw = _jaro_winkler_similarity(n1, n2)

        feat_core_lev = _levenshtein_ratio(c1, c2)
        feat_core_sort = _token_sort_ratio(c1, c2)
        feat_core_set = _token_set_ratio(c1, c2)
        feat_name_jaccard = _jaccard_similarity(ntok1, ntok2)

        is_addr_missing = 1.0 if (not a1 or not a2) else 0.0

        if is_addr_missing == 1.0:
            feat_addr_lev = 0.0
            feat_addr_jaccard = 0.0
        else:
            feat_addr_lev = _levenshtein_ratio(a1, a2)
            feat_addr_jaccard = _jaccard_similarity(atok1, atok2)

        postal_match = 1.0 if (post1 and post2 and post1 == post2) else 0.0

        num_overlap = 1.0 if (num1 and num2 and set(num1) & set(num2)) else 0.0

        country_match = 1.0 if (cntry1 and cntry2 and cntry1 == cntry2) else 0.0

        row_dict = {
            "source1_entity_id": s1_id,
            target_cand_col: target_id,
            "name_levenshtein_ratio": feat_name_lev,
            "name_jaro_winkler": feat_name_jw,
            "core_name_levenshtein_ratio": feat_core_lev,
            "core_name_token_sort_ratio": feat_core_sort,
            "core_name_token_set_ratio": feat_core_set,
            "name_token_jaccard": feat_name_jaccard,
            "address_levenshtein_ratio": feat_addr_lev,
            "address_token_jaccard": feat_addr_jaccard,
            "postal_code_match": postal_match,
            "address_number_match": num_overlap,
            "country_match": country_match,
            "is_address_missing": is_addr_missing,
        }
        feature_rows.append(row_dict)

    if not feature_rows:
        cols = [
            "source1_entity_id",
            target_cand_col,
            "name_levenshtein_ratio",
            "name_jaro_winkler",
            "core_name_levenshtein_ratio",
            "core_name_token_sort_ratio",
            "core_name_token_set_ratio",
            "name_token_jaccard",
            "address_levenshtein_ratio",
            "address_token_jaccard",
            "postal_code_match",
            "address_number_match",
            "country_match",
            "is_address_missing",
        ]
        return pd.DataFrame(columns=cols)

    return pd.DataFrame(feature_rows)
